import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-screen">
        <NavBar></NavBar>
        <div className="main h-3/4 mx-auto max-w-screen-2xl py-4 sm:px-6 lg:px-8">{children}</div>
      </body>
    </html>
  );
}
